### ISSUE TITLE
Loading Animation (p:ajaxStatus) does not disappear at table

### ISSUE THREAD

**Issue by m1rc0** [adminfaces/admin-starter#10]
Hi,

if I switch to another page on the car table, the loading animation does not disappear. As it seems to be defined in the admin template itself, I'm not sure how to modify it.

Sorry and thank you

**Comment by rmpestano** [comment]
Hi, can you detail the "switch to another page on the car table" ? can you reproduce here: http://admin-starter-admin-starter.1d35.starter-us-east-1.openshiftapps.com/admin-starter/

**Comment by m1rc0** [comment]
Hi and thank you.

After loading the cars page I use the pagination to show another set of items. The p:ajaxStatus appears but does not disappear. The data is loaded but greyed out. The same applies for using the filter. On the other hand the showcase works fine. 

![grafik](https://user-images.githubusercontent.com/1621265/45476188-a3471480-b73e-11e8-9168-4239875f2418.png)

I use Wildfly 14 orr Payra 5 if it matters.

Greetings

**Comment by rmpestano** [comment]
You've probably hit this issue: https://github.com/adminfaces/admin-template/issues/57

Update **Omnifaces to v3.x**, It may fix the issue.

**Comment by m1rc0** [comment]
It did. Thank you very much.
