### ISSUE TITLE
modify "content-header" in template

### ISSUE THREAD

**Issue by tulkas85** [adminfaces/admin-starter#12]
How can I modify "content-header" section in template ?
I want to add an img/icon to page description, and change font size.

**Comment by rmpestano** [comment]
Do you have an example to show what you want to do? what "content-header" section, this section: https://github.com/adminfaces/admin-template/blob/c9331aeb4aa39d58bbd9fb81ebc9dc52565dc987/src/main/resources/META-INF/resources/admin-base.xhtml#L81?

**Comment by rmpestano** [comment]
If yes, whereever it has a `<ui:insert name="someValue"` you can do a `ui:define="someValue"` on your page to add content to that template section

**Comment by rmpestano** [comment]
Maybe `<ui:define name="content-header"> your image</ui:define>` may do what you need but can't say for sure without more details.

**Comment by tulkas85** [comment]
![20190629_092558](https://user-images.githubusercontent.com/6707185/60381147-3cd27f00-9a50-11e9-9d5e-5d3994d123bf.png)
I want to add small icon on the left of title and set font size bigger

**Comment by rmpestano** [comment]
This should do the trick:

```
 <ui:define name="title">
        <i class="fa fa-car"/>
        <span style="font-size: 24px"> Car listing</span>
    </ui:define>
```

**Comment by tulkas85** [comment]
thank you !!!
