### ISSUE TITLE
How to implement password recovery

### ISSUE THREAD

**Issue by tulkas85** [adminfaces/admin-starter#15]
Hi, 
I'm using AdminStarter Project.
In order to implement password recovery on login, how can I by-pass AdminSession.isLoggedIn mechanism ?
I need to link from login page to an external page (passwordRecovery.xhtml)  without user is logged.
But  I am always redirected to login page.

**Comment by tulkas85** [comment]
I could use a fake user to force redirect to other page, and for this user I can block access to other page.
So now, I can send user to forgotPassword page, and I can send mail.
Now user receive e-mail, and I need to manage redirect to link in e-mail, something like 
https://ip:port/users/password/edit?reset_password_token=fZCr2zRt5DzQnxxx1FTo

But I can't access in method  LogonMB. isLoggedIn() to request url and parameters, I have nullPointerException on FacesContext.getCurrentInstance()

**Comment by rmpestano** [comment]
Hi there, use `admin.ignoredResources` in admin-config.properties:

```
admin.ignoredResources=/users/password/edit
```

More detais see here:https://adminfaces.github.io/docs/1.0.0/index.html#configuration

**Comment by tulkas85** [comment]
I set 
admin.ignoredResources=forgotPassword
where forgotPassword.xhtml is the page that filter must ignore. It's on same directory of login and index pages of admin-starter, but filter always redirect to login page

I try also :
admin.ignoredResources=/forgotPassword
admin.ignoredResources=/forgotPassword.xhtml
admin.ignoredResources=forgotPassword.xhtml

**Comment by rmpestano** [comment]
You can also change `isLoggedIn` logic in [LogonMB here](https://github.com/adminfaces/admin-starter/blob/ea218b5e62527bf601036e060c458be8bf581c83/src/main/java/com/github/adminfaces/starter/infra/security/LogonMB.java#L50) to return true if user is in forgotPassword page, ex:

```
  @Override
    public boolean isLoggedIn() {

        return currentUser != null || FacesContext.getCurrentInstance().getViewRoot().getViewId().equals("forgotPassword.xhtml");
    }

```

**Comment by tulkas85** [comment]
sorry
admin.ignoredResources=forgotPassword 
works.

In all test that I've done, FacesContext.getCurrentInstance() always null in isLoggedIn methods if user is not logged

**Comment by rmpestano** [comment]
I think in early request cycles It will be, adding a null check may do the trick.

Glad that the ignoreResources config works
