### ISSUE TITLE
When I pass the parameter opno #{schAttListMB.onChecked(c.opno)} , it passes an empty string rather than the required opno referenced from the datatable checkbox click event.

### ISSUE THREAD

**Issue by vbini21** [adminfaces/admin-starter#16]
<h:form>
            <p:focus context="@form"/>
            <div class="box box-primary">
                <div class="box-header with-border">
                    <p:dataTable widgetVar="patientsTable" var="c" value="#{schAttListMB.patients}" rows="5"
                                 rowKey="#{c.opno}" lazy="true" paginator="true"
                                 filteredValue="#{schAttListMB.filteredValue}">

                        <p:ajax event="rowSelectCheckbox" update="@(.ui-button, .ui-confirm-dialog)" listener="#{schAttListMB.onChecked(c.opno)}"/>
                        <p:ajax event="rowUnselectCheckbox" update="@(.ui-button, .ui-confirm-dialog)" listener="#{schAttListMB.onChecked(c.opno)}"/>
                        <p:ajax event="rowSelect" update="@(.ui-button, .ui-confirm-dialog)"/>
                        <p:ajax event="rowUnselect" update="@(.ui-button, .ui-confirm-dialog)"/>

                        
                        <p:column headerText="ID #" width="5%" filterBy="#{c.opno}" sortBy="#{c.opno}"
                                  filterMatchMode="contains">
                            <f:facet name="filter">
                                <p:autoComplete value="#{schAttListMB.filter.entity.opno}" forceSelection="true"
                                                minQueryLength="2" queryDelay="500" dropdown="true"
                                                completeMethod="#{schAttListMB.completeModelOpno}" maxResults="10">
                                    <p:ajax event="itemSelect" process="@this" update="@none"
                                            oncomplete="PF('patientsTable').filter()"/>
                                </p:autoComplete>
                            </f:facet>
                            <p:link value="#{c.opno}" >
                                <f:param name="opno" value="#{c.opno}"/>
                            </p:link>
                        </p:column>
                        

                        <p:column headerText="Present" selectionMode="multiple" styleClass="align-center" sortBy="#{c.status}"/>
                        <p:column headerText="Absent" selectionMode="multiple" styleClass="align-center" sortBy="#{c.status}"/>

                    </p:dataTable>
                </div>
            </div>

        </h:form>

**Comment by rmpestano** [comment]
Hi, this is a primefaces question, please use their forum.

For rowSelection events example see primefaces showcase here: https://www.primefaces.org/showcase/ui/data/datatable/selection.xhtml
