### ISSUE TITLE
Side menu disappears when resize window to minimum

### ISSUE THREAD

**Issue by emiliobristech** [adminfaces/admin-starter#3]
Hello, first of all, nice job! It's really useful!

Side menu items simply disappears when browser is resized to minimum width:

![image](https://user-images.githubusercontent.com/2892618/26933885-365ef7c8-4c3e-11e7-8d81-d19c9d1066a2.png)

You can test it resizing browser until menu gets in hiden state.

**Comment by rmpestano** [comment]
Hi @emiliobristech,

This is a [admin-template](https://github.com/adminfaces/admin-template/issues/18) issue, I've copied your issue there and should be fixed now. 

Can you try with latest snapshot?

Just enable maven snapshots in your pom:
``` 
<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

And use admin template 1.0.0-SNAPSHOT:

```
<dependency>
    <groupId>com.github.adminfaces</groupId>
    <artifactId>admin-template</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</dependency>
```

Thanks for your feedback!
