### ISSUE TITLE
LayoutMB.java has a wrong package

### ISSUE THREAD

**Issue by zezhayz** [adminfaces/admin-starter#4]
replace 
package com.github.adminfaces.showcase.bean;
by
package com.github.adminfaces.starter.bean;

**Comment by rmpestano** [comment]
Hi @zezhayz, 

where do you see this package declaration?

As I see in LayoutMB it is using 'starter' packge: https://github.com/adminfaces/admin-starter/blob/master/src/main/java/com/github/adminfaces/starter/bean/LayoutMB.java

Edit: Note that both applications, starter and showcase have its LayoutMB, here is showcase one: https://github.com/adminfaces/admin-showcase/blob/master/src/main/java/com/github/adminfaces/showcase/bean/LayoutMB.java

Maybe that's what confused you but layoutMB is an application specific class.

Thanks

**Comment by zezhayz** [comment]
Salam, 

Look at the clas LayoutMB on 'starter' project [https://github.com/adminfaces/admin-starter/blob/master/src/main/java/com/github/adminfaces/starter/bean/LayoutMB.java]
line 1 >> package com.github.adminfaces.showcase.bean;

you have to replace it by >> package com.github.adminfaces.starter.bean;

otherwise the IDE will notice an error, i've tried to run the starter poject on local server, and had to change the package line to have the projet to work.

Sorry for my humble english.

**Comment by rmpestano** [comment]
You are right, I got It now, thank you!

**Comment by zezhayz** [comment]
you're welcome :)
