### ISSUE TITLE
Mudar a cor da barra superior

### ISSUE THREAD

**Issue by GuiAAF** [adminfaces/admin-starter#5]
Olá, como posso mudar a cor da parra superior, ela é azul no momento, sou novo com o layout e gostaria da sua ajuda!!?
![barrasuperior](https://user-images.githubusercontent.com/33983826/33231704-d814a338-d1e0-11e7-8e3d-b0546d27ac03.PNG)

**Comment by rmpestano** [comment]
```
.skin-blue .main-header .navbar {
    background: red;
}

.skin-blue .main-header .logo {
    background: red;
}

.skin-blue a.dropdown-toggle {
    background: red!important;
}
```

O ideal é criar um skin nova, tem varias de exemplo aqui: https://github.com/adminfaces/admin-theme/tree/master/src/main/resources/less/admin-lte/skins

Assim que possível irei documentar como criar uma nova skin ([#107](https://github.com/adminfaces/admin-theme/issues/107)).
