### ISSUE TITLE
org.primefaces.model.LazyDataModel cannot be resolved

### ISSUE THREAD

**Issue by merlauz** [adminfaces/admin-starter#6]
The demo with primefaces 6.2 show this error The import org.primefaces.model.LazyDataModel cannot be resolved.
The demo work with primefaces 6.1

**Comment by rmpestano** [comment]
Hi @merlauz,

It is working form me, can you provide more details?

**Comment by merlauz** [comment]
It was an my Eclipse problem I apologize.
